Add new nuget publish for Utils.Testing to Action
trakx/dotnet-utils pull request #10
Opened 2020-12-23 19:47 UTC by carlos-takeapps

2020-12-24 04:59 UTC, monsieurleberre approved these changes

2020-12-24 05:30 UTC, monsieurleberre requested changes
thinking about it now, if we merge that PR in first, but have no code behind, it will simply fail...
can you please submit the rest of the code we need for that to work?

2020-12-24 05:30 UTC, monsieurleberre commented on .github/workflows/publish.nuget.yml
> +  TEST_PROJECT_PATH: "src/Trakx.Utils/Trakx.Utils.Testing.csproj"
In our others repos, this should be `src/Trakx.Utils.Testing/Trakx.Utils.Testing.csproj`

2020-12-24 05:59 UTC, carlos-takeapps commented on .github/workflows/publish.nuget.yml
> +  TEST_PROJECT_PATH: "src/Trakx.Utils/Trakx.Utils.Testing.csproj"
I fixed the path in a new commit

2020-12-24 06:00 UTC, carlos-takeapps commented
> thinking about it now, if we merge that PR in first, but have no code behind, it will simply fail...
> can you please submit the rest of the code we need for that to work?

I created a PR from the branch that has the new project

2020-12-28 21:32 UTC, carlos-takeapps commented
If we can merge this branch to dev, we will have the new publish package task available from the dev branch.

2020-12-29 08:06 UTC, monsieurleberre approved these changes

2020-12-29 08:21 UTC, merged